services:
 db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
 erase-service:
    build: .
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?sslmode=disable
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
       condition: service_healthy


volumes:
  postgresdata:
