services:
  database:
    container_name: database
    image: postgres:18-alpine
    restart: always
    env_file:
      - .env
    environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  general:
    container_name: general
    build: ./general
    env_file:
      - .env
    command: >
      sh -c "sleep 10 && python manage.py makemigrations authentication main posts votes &&
      python manage.py migrate &&
      python manage.py runserver"
    volumes:
      - ./general:/app
      - /app/.venv
    ports:
      - "4040:4040"
    depends_on:
      database:
        condition: service_healthy

  db_backup:
    container_name: db_backup
    build:
      context: ./general
      dockerfile: Dockerfile.backup
    env_file:
      - .env
    environment:
        POSTGRES_HOST : ${DB_HOST}
        POSTGRES_USER : ${DB_USER}
        POSTGRES_PASSWORD : ${DB_PASS}
        POSTGRES_DB : ${DB_NAME}
    volumes:
      - ./db_backups:/db_backups
      - ./backup.sh:/backup.sh
    entrypoint: ["sh", "/entrypoint.sh"]
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - general
    restart: unless-stopped

volumes:
  postgresql_data:
  db_backups:
