services:
  database:
    container_name: database
    image: postgres:18-alpine
    restart: always
    env_file:
      - .env
    environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgresql_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  general:
    container_name: general
    build: ./general
    env_file:
      - .env
    command: >
      sh -c "sleep 10 && python manage.py makemigrations authentication blocking posts votes &&
      python manage.py migrate &&
      python manage.py runserver"
    volumes:
      - ./general:/app
      - /app/.venv
    depends_on:
      database:
        condition: service_healthy

  auth:
    container_name: auth
    build: ./auth
    env_file: .env
    depends_on:
      database:
        condition: service_healthy

  password_generator:
    container_name: password_generator
    build: ./password_generator
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
      mail_service:
        condition: service_started

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - general
    restart: unless-stopped

  db_backup:
    container_name: db_backup
    build:
      context: ./general
      dockerfile: Dockerfile.backup
    env_file:
      - .env
    volumes:
      - ./db_backups:/db_backups
    entrypoint: ["sh", "/entrypoint.sh"]
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  mail_service:
    container_name: mail_service
    build: ./mail_sending
    env_file: .env
    depends_on:
      database:
        condition: service_healthy

  cleanup:
      container_name: cleanup
      build: ./cleanup
      env_file: .env
      environment:
        DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@database:5432/${DB_NAME}?sslmode=disable
      depends_on:
        database:
          condition: service_healthy

volumes:
  postgresql_data:
  db_backups:
