apiVersion: v1
kind: Secret
metadata:
  name: general-secret
  namespace: app
type: Opaque
stringData:
  DB_NAME: '{EXAMPLE}'
  DB_USER: '{EXAMPLE}'
  DB_PASS: '{EXAMPLE}'
  DB_HOST: '{EXAMPLE}'
  JWT_KEY: '{EXAMPLE}'
  SECRET_KEY: '{EXAMPLE}'
  AWS_ACCESS_KEY_ID: '{EXAMPLE}'
  AWS_SECRET_ACCESS_KEY: '{EXAMPLE}'
  AWS_REGION: '{EXAMPLE}'
  AWS_STORAGE_BUCKET_NAME: '{EXAMPLE}'
