apiVersion: v1
kind: Secret
metadata:
  name: general-secret
  namespace: app
type: Opaque
stringData:
  DB_NAME: 'supernatural_db'
  DB_USER: 'master'
  DB_PASS: 'SuPeRnAtUrAldataBASE'
  DB_HOST: 'microservice-db.cgbwawymgiu3.us-east-1.rds.amazonaws.com'
  JWT_KEY: '{EXAMPLE}'
  SECRET_KEY: '{EXAMPLE}'
  AWS_ACCESS_KEY_ID: '{EXAMPLE}'
  AWS_SECRET_ACCESS_KEY: '{EXAMPLE}'
  AWS_REGION: '{EXAMPLE}'
  AWS_STORAGE_BUCKET_NAME: '{EXAMPLE}'
