apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-generator
  template:
    metadata:
      labels:
        app: password-generator
    spec:
      serviceAccountName: password-protection
      containers:
        - name: password-generator
          image: 704427427594.dkr.ecr.us-east-1.amazonaws.com/password_generator:test_password_generator_v.306
          envFrom:
            - secretRef:
                name: password-generator-secret
