apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cleanup.nameDeployment }}
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.cleanup.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.cleanup.appLabel }}
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/connect-service: '{{ .Values.cleanup.connectService }}'
    spec:
      serviceAccountName: {{ .Values.cleanup.serviceAccountName }}
      containers:
        - name: {{ .Values.cleanup.containerName }}
          image: {{ .Values.cleanup.image }}
          ports:
            - containerPort: {{ .Values.cleanup.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.cleanup.nameSecret }}
          resources:
            requests:
             cpu: "150m"
             memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.cleanup.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
             path: /health
             port: {{ .Values.cleanup.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 15
