apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cleanup.nameSecret }}
  namespace: app
type: Opaque
stringData:
  DSN: '{{ .Values.cleanup.DSN }}'
  JWT_KEY: '{{ .Values.cleanup.JWT_KEY }}'
  DB_NAME: '{{ .Values.cleanup.DB_NAME }}'
  DB_USER: '{{ .Values.cleanup.DB_USER }}'
  DB_PASS: '{{ .Values.cleanup.DB_PASS }}'
  DB_HOST: '{{ .Values.cleanup.DB_HOST }}'
  SECRET_KEY: '{{ .Values.cleanup.SECRET_KEY }}'
  AWS_ACCESS_KEY_ID: '{{ .Values.cleanup.AWS_ACCESS_KEY_ID }}'
  AWS_SECRET_ACCESS_KEY: '{{ .Values.cleanup.AWS_SECRET_ACCESS_KEY }}'
  AWS_REGION: '{{ .Values.cleanup.AWS_REGION }}'
  AWS_STORAGE_BUCKET_NAME: '{{ .Values.cleanup.AWS_STORAGE_BUCKET_NAME }}'
  EMAIL_FROM: '{{ .Values.cleanup.EMAIL_FROM }}'
  EMAIL_PASSWORD: '{{ .Values.cleanup.EMAIL_PASSWORD }}'
  EMAIL_PORT: '{{ .Values.cleanup.EMAIL_PORT }}'
