apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cleanup.nameService }}
  namespace: app
spec:
  selector:
    app: {{ .Values.cleanup.appLabel }}
  ports:
  - port: {{ .Values.cleanup.containerPort }}
    targetPort: {{ .Values.cleanup.containerPort }}
  type: ClusterIP
