#default values
global:
  env: dev
services:
  cleanup:
    #specifying if service should have HorizontalAutoScaling and Service
    hasHorizontalAutoScaling: true
    hasService: true
    hasSecret: true

    # deployment vars
    nameDeployment: cleanup-deployment
    appLabel: cleanup
    isPartOfConsul: true
    connectService: cleanup  #for mail it's mail-service
    serviceAccountName: cleanup #for mail it's mail-service
    containerName: cleanup
    image: 704427427594.dkr.ecr.us-east-1.amazonaws.com/cleanup:test_cleanup_v.281
    containerPort: 8585 #used for container port and liveness port
    getCheck: true
    nameSecret: cleanup-secret
    #horizontal_auto_scaling vars
    nameAutoscaler: cleanup-autoscaler
    #name-secret used here
    DSN: '{EXAMPLE}'
    nameService: cleanup-service

  auth:
    hasHorizontalAutoScaling: true
    hasService: true
    hasSecret: true
    # deployment vars

    nameDeployment: auth-deployment
    appLabel: auth
    partOfConsul: true
    connectService: auth

    serviceAccountName: auth #for mail it's mail-service
    containerName: auth
    image: 704427427594.dkr.ecr.us-east-1.amazonaws.com/auth:test_auth_v.293
    containerPort: 8080 #used for container port and liveness port
    getCheck: true
    nameSecret: auth-secret

    #horizontal_auto_scaling vars
    nameAutoscaler: auth-autoscaler
    #name-deployment as a var used here

    #secret vars
    #name-secret used here
    DSN: '{EXAMPLE}'
    JWT_KEY: '{EXAMPLE}'
    # service_account vars
    #serviceAccountName used here for mail = mail-service

    #service vars
    #container-port used here x2
    nameService: auth-service
    #app-label used here

  mail:
      #specifying if service should have HorizontalAutoScaling and Service
    hasHorizontalAutoScaling: true
    hasService: true
    hasSecret: true

    # deployment vars
    nameDeployment: mail-deployment
    appLabel: mail
    isPartOfConsul: true
    connectService: mail-service  #for mail it's mail-service
    serviceAccountName: mail-service #for mail it's mail-service
    containerName: mail
    image: 704427427594.dkr.ecr.us-east-1.amazonaws.com/mail_sending:test_mail_sending_v.293
    containerPort: 8074 #used for container port and liveness port
    getCheck: true
    nameSecret: mail-secret
    #horizontal_auto_scaling vars
    nameAutoscaler: mail-autoscaler
    #secret vars
    #name-secret used here
    DSN: '{EXAMPLE}'
    EMAIL_FROM: '{EXAMPLE}'
    EMAIL_PASSWORD: '{EXAMPLE}'
    EMAIL_PORT: '{EXAMPLE}'
    #service vars
    nameService: mail-service

  frontend:
    #specifying if service should have HorizontalAutoScaling and Service
    hasHorizontalAutoScaling: true
    hasService: true
    hasSecret: false
    # deployment vars
    nameDeployment: frontend-deployment
    appLabel: frontend
    isPartOfConsul: true
    connectService: frontend  #for mail it's mail-service
    serviceAccountName: frontend #for mail it's mail-service
    containerName: frontend
    image: 704427427594.dkr.ecr.us-east-1.amazonaws.com/frontend:test_frontend_v.282
    containerPort: 8080 #used for container port and liveness port
    getCheck: true
    #horizontal_auto_scaling vars
    nameAutoscaler: frontend-autoscaler
    #secret vars
    #service vars
    nameService: frontend-service

  general:
    #specifying if service should have HorizontalAutoScaling and Service
    hasHorizontalAutoScaling: true
    hasService: true
    hasSecret: true

    # deployment vars
    nameDeployment: general-deployment
    appLabel: general
    isPartOfConsul: true
    connectService: general  #for mail it's mail-service
    serviceAccountName: general #for mail it's mail-service
    containerName: general
    image: 704427427594.dkr.ecr.us-east-1.amazonaws.com/general:test_general_v.282
    containerPort: 4040 #used for container port and liveness port
    getCheck: true
    nameSecret: general-secret
    #horizontal_auto_scaling vars
    nameAutoscaler: general-autoscaler
    #secret vars
    #name-secret used here
    JWT_KEY: '{EXAMPLE}'
    DB_NAME: '{EXAMPLE}'
    DB_USER: '{EXAMPLE}'
    DB_PASS: '{EXAMPLE}'
    DB_HOST: '{EXAMPLE}'
    SECRET_KEY: '{EXAMPLE}'
    AWS_ACCESS_KEY_ID: '{EXAMPLE}'
    AWS_SECRET_ACCESS_KEY: '{EXAMPLE}'
    AWS_REGION: '{EXAMPLE}'
    AWS_STORAGE_BUCKET_NAME: '{EXAMPLE}'
    #service vars
    nameService: general-service

  password_generator:
     #specifying if service should have HorizontalAutoScaling and Service
    hasHorizontalAutoScaling: false
    hasService: false
    hasSecret: true

    # deployment vars
    nameDeployment: password-generator-deployment
    appLabel: password-generator
    isPartOfConsul: false
    serviceAccountName: password-protection #for mail it's mail-service
    containerName: password-generator
    image: 704427427594.dkr.ecr.us-east-1.amazonaws.com/password_generator:test_password_generator_v.269
    containerPort: 9058 #dummy port #used for container port and liveness port
    getCheck: false
    nameSecret: password-generator-secret

    #secret vars
    #name-secret used here
    DSN: '{EXAMPLE}'
