apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 704427427594.dkr.ecr.us-east-1.amazonaws.com/auth:test_auth_v.235
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: auth-secret
