apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  DSN: 'host=database port=5432 user=master password=SuPeRnAtUrAldataBASE dbname=supernatural_db sslmode=disable'
  JWT_KEY: 'SuPeRnAtUrAlJwTkEy'
