apiVersion: v1
kind: Secret
metadata:
  name: cleanup-secret
  namespace: app
type: Opaque
stringData:
  DSN: 'host={RDS_PORT} port=5432 user={EXAMPLE} password={EXAMPLE} dbname={EXAMPLE} sslmode=require'
