apiVersion: v1
kind: Secret
metadata:
  name: cleanup-secret
  namespace: app
type: Opaque
stringData:
  DSN: 'host=microservice-db.cgbwawymgiu3.us-east-1.rds.amazonaws.com port=5432 user=master password=SuPeRnAtUrAldataBASE dbname=supernatural_db sslmode=require'
