apiVersion: v1
kind: Pod
metadata:
  name: testingpods
  labels:
    test: testing
spec:
  containers:
    - name: test
      image: 704427427594.dkr.ecr.us-east-1.amazonaws.com/cleanup:test_cleanup_v.239
      ports:
        - containerPort: 8585
      # envFrom:
      #   - secretRef:
      #       name: cleanup-secret
      env:
        - name: DSN
          value: "host=db port=5432 user=master password=SuPeRnAtUrAldataBASE dbname=supernatural_db sslmode=disable"

    - name: db
      image: postgres:18-alpine
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: supernatural_db
        - name: POSTGRES_USER
          value: master
        - name: POSTGRES_PASSWORD
          value: SuPeRnAtUrAldataBASE
