apiVersion: v1
kind: Secret
metadata:
  name: mail-secret
  namespace: app
type: Opaque
stringData:
  DSN: '{EXAMPLE}'
  EMAIL_FROM: '{EXAMPLE}'
  EMAIL_PASSWORD: '{EXAMPLE}'
  EMAIL_PORT: '{EXAMPLE}'
  EMAIL_HOST: '{EXAMPLE}'
