apiVersion: v1
kind: Secret
metadata:
  name: mail-secret
  namespace: app
type: Opaque
stringData:
  DSN: '{EXAPMLE}'
  EMAIL_FROM: '{EXAPMLE}'
  EMAIL_PASSWORD: '{EXAPMLE}'
  EMAIL_PORT: '{EXAPMLE}'
